version: "3.8"

services:
  chatbot:
    build: .
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=your_openai_api_key
      - GCLOUD_KEY_PATH=/app/path/to/your/keyfile.json
      - VOICEVOX_API_URL=http://localhost:50021
      - SPEAKER_ID=0

